### ISSUE TITLE
player.destroy() doesn't work for DASH

### ISSUE THREAD

**Issue by ibreakstuff93** [clappr/dash-shaka-playback#14] opened 2016-06-24 15:02 UTC
Hi,

Using player version 0.2.56, if calling the player.destroy() javascript, the playback stops but the player body remains on the page.

This is only when using the DASH configuration, it works great when playing back HLS.

**Comment by leandromoreira** [comment] 2016-06-24 19:02
@ibreakstuff93 thanks I can reproduce it here https://jsfiddle.net/hzzurtkh/

**Comment by leandromoreira** [comment] 2016-06-25 02:09
@ibreakstuff93 I cloned the shaka project to try to reproduce the same error (aka call `destroy`) but I couldn't, either on the HEAD or the tag 2.0.7-beta.

@joeyparrish maybe you can help us here, I'm calling the player destroy and then the success promise is executed... but after that a weird error shows up at console `Uncaught TypeError: Cannot read property 'abr' of null`

```
    /// _player is an instance of shaka
    this._player.destroy().then(() => console.log('success'), () => console.log('error') )
```
I saw it was raising this error on the last line of this snippet. (probably because `a.a` was undefined)
```javascript
                                function ne(a) {
                                    a.u && a.u.Y(a.A, "sourceopen");
                                    a.c && (a.c.removeAttribute("src"),
                                    a.c.load());
                                    var b = Promise.all([a.a.abr.manager.stop(), a.g ? a.g.s() : null , a.O ? a.O.s() : null , a.h ? a.h.s() : null , a.b ? a.b.s() : null , a.o ? a.o.stop() : null ]);
```

But again I couldn't reproduce this behavior while on the HEAD or at the tag tag 2.0.7-beta using solely Shaka.

**Comment by leandromoreira** [comment] 2016-06-25 02:33
I think I have a clue, we're removing the DOM element (video) on the `destroy` success, maybe it's not safe.

**Comment by joeyparrish** [comment] 2016-06-25 03:34
Hrm... 2.0.7-beta isn't a tag in our repo.  Is that one of yours in clappr?

Just based on the log `Uncaught TypeError: Cannot read property 'abr' of null`, I assume this is a bug where something the `'abr'` member of the configuration object is accessed after the config has been set to `null` by `destroy()`.

The compiled snippet you mentioned looks like the body of `Player.prototype.destroy()` itself.  What we have there in HEAD is:

```js
  var p = Promise.all([
    this.config_ ? this.config_.abr.manager.stop() : null,
```

3 weeks ago, before the commit ["Overhaul load/unload/destroy"](https://github.com/google/shaka-player/commit/a644900f0f30968d3e56dc9aca482b4fc13d7e95), we had only this:

```js
  var p = Promise.all([
    this.config_.abr.manager.stop(),
```

So prior to that overhaul, multiple calls to `destroy()` might result in that TypeError.

I think the best solution is to move to a version that includes the overhauled `destroy()`.  Shaka Player v2.0.0-beta3 will have this commit.  I can ping this ticket when it's out, if that's helpful.

The next best solution is to make sure that you do not call `destroy()` more than once on the same `Player` instance.  This should effectively work around the bug until you upgrade to a fixed version of Shaka.

**Comment by leandromoreira** [comment] 2016-06-25 03:51
> Hrm... 2.0.7-beta isn't a tag in our repo. Is that one of yours in clappr?

yep, my mistake in fact I checkout to `v2.0.0-beta2`

> Shaka Player v2.0.0-beta3 will have this commit. I can ping this ticket when it's out, if that's helpful.

It'll be! Thanks

**Comment by leandromoreira** [comment] 2016-06-27 17:32
@ibreakstuff93 this will be fixed when a newer version will be published

**Comment by ibreakstuff93** [comment] 2016-06-28 15:20
@leandromoreira thanks for your awesome work!

**Closed** 2016-06-28 16:44 UTC
Labels: bug, wontfix

**Comment by ibreakstuff93** [comment] 2016-06-29 07:53
@leandromoreira - sorry for being a n00b here, is this tagged as wontfix as the problem lies on the clappr side - and if I go to the latest version of Clappr it will work? Sorry for being a thickie!

**Comment by leandromoreira** [comment] 2016-06-29 11:33
@ibreakstuff93 yes, I fixed this at https://github.com/clappr/clappr/pull/1047 and when a new clappr version came out this will be fixed :)

**Comment by joeyparrish** [comment] 2016-08-13 16:43
JFYI, Shaka Player v2.0.0-beta3 came out recently with [the fix mentioned above](https://github.com/clappr/dash-shaka-playback/issues/14#issuecomment-228507159).

**Comment by leandromoreira** [comment] 2016-08-13 22:07
Thanks @joeyparrish I'll try to use the last one now lol
